version: 0.0
os: linux
files:
  - source: /
    destination: /home/app
    overwrite: true
permissions:
  - object: /home/app
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: codedeploy/app_start.sh
      timeout: 180
      runas: root
