version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing yarn
      - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
      - yum install yarn
  pre_build:
    commands:
      - echo Installing Dependencies
      - yarn
  build:
    commands:
      - yarn nest start
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: .
