version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing yarn
      - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
      - yum install yarn -y
  pre_build:
    commands:
      - rm -rf node_modules
      - echo Installing dependencies
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - mkdir -p /home/ec2-user/services
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: .
