version: 0.2
phases:
  install:
    commands:
      - echo Installing NodeJS
      - curl https://raw.githubusercontent.com/creationix/nvm/v0.25.0/install.sh | bash
      - "export NVM_DIR='/root/.nvm'"
      - "[ -s '$NVM_DIR/nvm.sh' ] && . '$NVM_DIR/nvm.sh'"
      - nvm install 12.12.0 && nvm alias default 12.12.0
      - echo Installing nvm
      - curl -s https://raw.githubusercontent.com/tophat/yvm/master/scripts/install.js | node
      - yvm install latest
      - yvm use latest
  pre_build:
    commands:
      - echo Installing Dependencies
      - yarn
  build:
    commands:
      - yarn nest start
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: .
